class ReactEmployeePageLocators:
    USERNAME_INPUT = "input[name='username']"
    PASSWORD_INPUT = "input[name='password']"
    SUBMIT_BUTTON = "button[type='submit']"
    DASHBOARD = "#dashboard"
    AVATAR_MENU = "#avatar-menu"
    ORDER_ID_LINK = "a.order-id"
    NEW_ORDER_BUTTON = "#new-order-button"
    ORDER_DETAILS = "#order-details"
    DOWNLOAD_BUTTON = "#download-button"
    ACCOUNT_SECTION = "#account-section"
    CHANGE_PASSWORD_BUTTON = "#change-password-button"
    HELP_CENTER = "#help-center"
    CONTACT_US = "#contact-us"
    LOGOUT_BUTTON = "#logout-button"
