class ReactClientPageLocators:
    USERNAME_INPUT = "input[name='username']"
    PASSWORD_INPUT = "input[name='password']"
    SUBMIT_BUTTON = "button[type='submit']"
    DASHBOARD = "#dashboard"
    SEARCH = "#dashboard-search"
    ORDER_DETAILS = "#order-details"
    DOWNLOAD_BUTTON = "#download-button"
    NEW_ORDER_BUTTON = "#new-order-button"
    AVATAR_MENU = "#avatar-menu"
    HELP_CENTER = "#help-center"
    CONTACT_US = "#contact-us"
    FOOTER = "#footer"
    LOGOUT_BUTTON = "#logout-button"
    ORDER_ID_LINK = "a.order-id"
