class ReactVerifierPageLocators:
    USERNAME_INPUT = "input[name='username']"
    PASSWORD_INPUT = "input[name='password']"
    SUBMIT_BUTTON = "button[type='submit']"
    DASHBOARD = "#dashboard"
    GRID_VIEW = "#grid-view"
    ACCOUNT_DETAIL = "#account-detail"
    HELP_CENTER = "#help-center"
    CONTACT_US = "#contact-us"
    ADD_CC_BUTTON = "#add-cc"
    DELETE_CC_BUTTON = "#delete-cc"
    EDIT_CC_BUTTON = "#edit-cc"
    LOGOUT_BUTTON = "#logout-button"
    ORDER_ID_LINK = "a.order-id"
    ORDER_DETAILS = "#order-details"
    DOWNLOAD_BUTTON = "#download-button"
